### PR TITLE
Move from incremental i32 user ids to uuids. r=fabrice

### PR DESCRIPTION
**Pull request by ferjm**
r? @arcturus 

The reason to do this change is because we are using the id of the user for the PUT /user/:id/activate request and incremental i32 ids are pretty easy to guess.

### CODE REVIEW

**Comment by fabricedesre** [comment]
Do you mean PUT /users/:id/activate documented at https://github.com/fxbox/users/blob/master/doc/API.md#put-usersidactivate ?
Maybe the only thing we need is to **not** return a precise error on failure to prevent the attacker from learning too much?

**Comment by arcturus** [comment]
I agree on not giving enough information to an attacker, but we need as well to not to have easy ids that could be easily generated by a script.

**Comment by ferjm** [comment]
Yes, sorry, I meant PUT instead of GET.

Even if we don't return the precise error, it is still very tempting to poll for `/users/2/activate` until it does not throw an error.

We also need to implement a backoff protocol to allow individual clients to issue too many requests in quick succession. That will also help to secure this endpoint.

**Comment by fabricedesre** [comment]
How would polling `PUT /users/2/activate` not return an error if you don't know the password?

**Comment by ferjm** [comment]
`PUT /users/:id/activate` allows to set the user password. So any string would work if the (inactive) user exists.

**Comment by fabricedesre** [comment]
Right, but only the admin user or the user itself should be able to do this password change.

**Comment by ferjm** [comment]
This is not a password change. At this point the user has not set his password yet.

The flow is:
1. Admin user creates a new (inactive) user with the user email via [POST /users](https://github.com/fxbox/users/blob/master/doc/API.md#post-users).
2. The email owner receives an invitation email with the activation link which is going to be something like `https://<foxbox-public-url>/users/:id/activate`. A GET request to this page will load a foxbox hosted page with a UI that will allow the user to set his display name and password (if the user has not already being activated, this can be checked via `GET /users/:id`). This page will be the one doing the actual `PUT /users/:id/activate`.

Note that sending the email and the user activation UI are not implemented yet as these needs to be done outside of this repo, as part of foxbox' static content.

**Comment by ferjm** [comment]
More discussion happened on IRC.

> [19:09:38]  <~fabrice>    ferjm: why not enforce that when the admin creates a user, it sets a random password and that needs to be communicated to the user?
> [19:10:53]  <ferjm> fabrice that's another option, but worst UX (copy&paste password)
> [19:11:17]  <ferjm> we could generate a one shot token instead
> [19:11:23]  <ferjm> and append it to the url
> [19:12:00]  <~fabrice>  yep
> [19:14:52]  <~fabrice>  that would be better
> [19:18:36]  <ferjm> ok, but I still have the feeling that having easy guessable user ids is not a good idea :\
> [19:19:01]  <ferjm> a brute force attack will be simpler with incremental user ids for example

**Comment by ferjm** [comment]
@fabricedesre @arcturus I agree with adding a temporary token for user activation as additional security measure, but are you ok with moving forward with the change from incremental i32 ids to uuids?

**Comment by fabricedesre** [comment]
I'm neutral. Unconvinced that we really need that, but I won't veto if both of you want it.

**Comment by ferjm** [comment]
@fabricedesre since @arcturus is on PTO, would you mind taking a look at this patch, please? Thanks!

**Comment by fabricedesre** [comment]
r=me

**Comment by ferjm** [comment]
Thanks!

**Pull request merged**
