### PR TITLE
Get rid of not implemented endpoints. r=francisco

### PR DESCRIPTION
**Pull request by ferjm**

### CODE REVIEW

**Comment by arcturus** [comment]
@ferjm do we have an extra commits right? I think this is mixing all the commits in the PR 32. Or I'm missing something :)

**Comment by ferjm** [comment]
Yeah, sorry about that. The order of the PR is #24, #31, #32

**Comment by arcturus** [comment]
There we are, here is a conflict since this branch includes the commits from #24, this should have just commit  2161f91

**Comment by arcturus** [comment]
https://github.com/ferjm/users/commit/2161f91d5c961b2e5a4f8fac2eeba03ac6791a3a looks good to me, please rebase and merge :)

**Pull request merged**
